markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : a blog about nothing
production_url : http://chadsbrown.github.com
description: "Much ado about nothing."
disqus_shortname: chadsbrownblog
analytics: 
gauges: 
author :
  name : Chad Brown
  github : chadsbrown
  twitter : chadsbrown
